version: '3'
services:
  app:
    build: .
    command: ["/sbin/marine-sky"]
    ports:
      - "8888:8888"
    volumes:
      - ./sky:/sky
    environment:
      PORT: "8888"
      DEST: "/sky"
      LANG: "C.UTF-8"
    tty: true
    stdin_open: true
