name:                marine-sky
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/marine-sky#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - safe

library:
  source-dirs:
    - src
  dependencies:
    # Container
    - containers

    # Renamer, File
    - directory
    - filepath
    - unix

    # HTTP, Env
    - http-client
    - http-client-tls

    # HTTP
    - bytestring
    - utf8-string
    - http-types

executables:
  marine-sky:
    source-dirs:
      - app
    main:            Main.hs
    ghc-options:     -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - marine-sky
      - scotty
      - aeson
      - transformers
      - wai-cors

tests:
  marine-sky-test:
    source-dirs:
      - test
    main:            Spec.hs
    dependencies:
      - marine-sky
      - hspec
      - QuickCheck
    ghc-options:     -threaded -rtsopts -with-rtsopts=-N

github: githubuser/marine-sky
