name:                marine-sky
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/marine-sky#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers

library:
  source-dirs:
    - src
  dependencies:
    - directory
    - filepath
    - unix

executables:
  marine-sky:
    source-dirs:
      - app
    main:            Main.hs
    ghc-options:     -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - marine-sky
      - scotty
      - aeson
      - transformers

tests:
  marine-sky-test:
    source-dirs:
      - test
    main:            Spec.hs
    dependencies:
      - marine-sky
      - hspec
      - QuickCheck
    ghc-options:     -threaded -rtsopts -with-rtsopts=-N

github: githubuser/marine-sky
